version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

volumes:
  pgdata: