spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://postgres-db:5432/homework

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt-secret-key: ${JWT_SECRET_KEY}
jwt-expiration-time: ${JWT_EXPIRATION_TIME}

logging:
  level:
    root: INFO
    com.homework: DEBUG
