spring:
  application:
    name: basic
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:${POSTGRES_DB}:5432

server:
    port: 8080
